### ISSUE TITLE
If there's no path available the script fail

### ISSUE THREAD

**Issue by AlbertoCentonze** [RiccardoTancredi/A_Star_Pathfinding#2]
As I said in the title you should handle the case in which there's no way to reach the endpoint.

**Comment by RiccardoTancredi** [comment]
Thank you very much for the issue. I have now resolved in the last commit

**Comment by RiccardoTancredi** [comment]
![Error message](https://user-images.githubusercontent.com/69259286/95141542-cb649e80-0771-11eb-8811-5e213f06533f.png)
Here it is
