### ISSUE TITLE
Bug in the A* algorithm

### ISSUE THREAD

**Issue by AlbertoCentonze** [RiccardoTancredi/A_Star_Pathfinding#3]
I just randomly found a wrong path using the algorithm. I'll attach a screenshot to help you replicate the issue.

![Screenshot (26)](https://user-images.githubusercontent.com/11707683/94442501-54913980-01a4-11eb-8fed-6ba841e54282.png)

**Comment by RiccardoTancredi** [comment]
Thank you very much for the issue. It has been corrected in the last commit

**Comment by RiccardoTancredi** [comment]
![A_start Special Case](https://user-images.githubusercontent.com/69259286/95141299-0d411500-0771-11eb-8a4d-3f4bfe7d8413.png)
This is an example. But actually the issue is still open, because all of those green cells are drawn. I have to figure it out better. Thank you

**Comment by RiccardoTancredi** [comment]
![Issue#3](https://user-images.githubusercontent.com/69259286/95202872-35b52780-07e2-11eb-9f28-a45756d2ab73.png)
In the last commit this issue has been solve as you can see here, where I recreate the problem you found.
Thank you very much for the report.
